# Generated by Django 5.0.6 on 2024-05-15 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=400)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('data_vencimento', models.DateField()),
                ('situacao', models.CharField(choices=[('A', 'Aberto'), ('P', 'Pago'), ('V', 'Vencida')], max_length=1)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Saida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateField()),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.conta')),
            ],
        ),
    ]
