# Generated by Django 5.0.6 on 2024-05-15 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
