# Generated by Django 5.0.6 on 2024-05-18 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_conta_observacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='situacao',
            field=models.CharField(choices=[('A', 'Aberto'), ('P', 'Pago'), ('V', 'Vencida')], default='A', max_length=1),
        ),
    ]
