# Generated by Django 5.0.6 on 2024-05-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_conta_situacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='cod_barra',
            field=models.CharField(default='Não Disponível', max_length=250),
        ),
    ]
